version: '3.1'

services:
    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: dev
            POSTGRES_PASSWORD: postgres
    user:
        image: dev.alan/user-api
        ports:
            - "8080:8080"
        environment:
            POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        depends_on:
            - postgres
    product:
        image: dev.alan/product-api
        ports:
            - "8081:8081"
        environment:
            POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        depends_on:
            - postgres
    shopping:
        image: dev.alan/shopping-api
        ports:
            - "8082:8082"
        environment:
            POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PRODUCT_API_URL: http://product:8081/products
            USER_API_URL: http://user:8080/users
        depends_on:
            - postgres             
